### ISSUE TITLE
Can you correct a typo on the wall?

### ISSUE THREAD

**Issue by wei-peng-47** [alexa/dstqa#1]
Hi, 
There is a typo on the wall w.r.t pre-calculate ELMO embedding. It took the whole night run without generating any embeddings:

bash calc_elmo.sh ./data ./data/elms_embeddings

should be

bash calc_elmo.sh ./data ./data/elmo_embeddings

Regards,

W.

**Comment by ultralisksu** [comment]
thank you, just fixed it.
